### ISSUE TITLE
create a footer

### ISSUE THREAD

**Issue by Kamil-Drozdz** [coders-factory-com/cf-frontend#45]
create a footer as different organizations similar to ours

**Comment by kasin-it** [comment]
![obraz](https://github.com/coders-factory-com/cf-frontend/assets/89151689/780001f4-154f-4e3f-bd6d-57b580cd7e74)
You mean something like this?

**Comment by kasin-it** [comment]
@Kamil-Drozdz, should I add new provider icons to the footer? The GitHub icon is not visible enough.


![obraz](https://github.com/coders-factory-com/cf-frontend/assets/89151689/62499c50-ce0d-4f26-944e-b0e84aaa68d4)
![obraz](https://github.com/coders-factory-com/cf-frontend/assets/89151689/7dabb3c5-3269-4aac-b6f8-f06c297adbfe)
![obraz](https://github.com/coders-factory-com/cf-frontend/assets/89151689/05fe15b3-af06-4162-aeae-a900466b396b)

**Comment by Kamil-Drozdz** [comment]
I highly recommend using the react-icons library at this moment, as we can utilize icons like Facebook and Google from the FaSquares collection. The biggest advantage is that it will ensure uniformity in size across all icons, and we'll also have the ability to manage their colors. Additionally, I think the icons should be aligned on the same line as 'Coders-Factory' for a more cohesive look.
![Bez tytułu111](https://github.com/coders-factory-com/cf-frontend/assets/108432936/c8ad39fb-8349-4d61-b4f8-4db249067aad)

the rest will be  improved during CR, remember to upload the changes on a separate branch created here
![image](https://github.com/coders-factory-com/cf-frontend/assets/108432936/5181c927-6bef-41a5-ad69-0f0b041e069e)
